### ISSUE TITLE
mixcell ./install.sh errors - symbolic links

### ISSUE THREAD

**Issue by badmanwillis** [clebercoutof/mixcell#4]
I've been trying to get mixcell running for over the last week, without sucess, and have now pinpointed the problem (i think), these errors occur on multiple computers, (all running Ubuntu 16.04 LTS).

When running ./install.sh the following errors occur.

First, when "cloning into dynamixelsdk"
`olly@olly-Lenovo-G770:~$ cd mixcell/install/
olly@olly-Lenovo-G770:~/mixcell/install$ ./install.sh
Cloning into 'DynamixelSDK'...
remote: Counting objects: 11615, done.
remote: Compressing objects: 100% (373/373), done.
remote: Total 11615 (delta 297), reused 546 (delta 237), pack-reused 10944
Receiving objects: 100% (11615/11615), 27.28 MiB | 524.00 KiB/s, done.
Resolving deltas: 100% (6552/6552), done.
Checking connectivity... done.
ln: failed to create symbolic link 'mixcell': File exists
python-dbus-dev - main loop integration development files for python-dbus
python3-pyudev - Python3 bindings for libudev
eric - full featured Python IDE`

And after entering my password
`Reading package lists... Done
Building dependency tree       
Reading state information... Done`

...

`cp "./libdxl_x64_c.so" "/usr/local/lib/libdxl_x64_c.so"
ln -s "/usr/local/lib/libdxl_x64_c.so" "/usr/local/lib/libdxl_x64_c.so.2"
ln: failed to create symbolic link '/usr/local/lib/libdxl_x64_c.so.2': File exists
Makefile:79: recipe for target 'install' failed
make: [install] Error 1 (ignored)
ln -s "/usr/local/lib/libdxl_x64_c.so" "/usr/local/lib/libdxl_x64_c.so.2.0"
ln: failed to create symbolic link '/usr/local/lib/libdxl_x64_c.so.2.0': File exists
Makefile:79: recipe for target 'install' failed
make: [install] Error 1 (ignored)
ln -s "/usr/local/lib/libdxl_x64_c.so" "/usr/local/lib/libdxl_x64_c.so.2.0.0"
ln: failed to create symbolic link '/usr/local/lib/libdxl_x64_c.so.2.0.0': File exists
Makefile:79: recipe for target 'install' failed
make: [install] Error 1 (ignored)
cp -r ../../include/dynamixel_sdk/* /usr/local/include/dynamixel_sdk/
ldconfig
/home/olly/mixcell'`

So imo this is not an end-user problem, as i've had colleagues experience the same issue, and the problem is the same on multiple computers.

Fwiw, if you attempt to run  mixcell ignoring these problems:
`olly@olly-Lenovo-G770:~$ mixcell
Traceback (most recent call last):
  File "/home/olly/mixcell/QTCode/mixcell", line 9, in <module>
    import source_code as mixcell
  File "/home/olly/mixcell/source_code/source_code.py", line 33, in <module>
    import dynamixel_functions as dynamixel                     # Uses Dynamixel SDK library
  File "/home/olly/mixcell/source_code/dynamixel_functions.py", line 55, in <module>
    printTxRxResult = dxl_lib.printTxRxResult
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libdxl_x64_c.so: undefined symbol: printTxRxResult
`

**Comment by clebercoutof** [comment]
I'll check on the symbolic link problem, the problem that shows up when you try to run it without the happened because ROBOTIS changed it's SDK, i'll change the code to adapt to it

**Comment by clebercoutof** [comment]
@badmanwillis I've fixed the problem related to the SDK version, there is a reinstall.sh file which fix the SDK version problem. I'll try to fix the symbolic link problem now

**Comment by badmanwillis** [comment]
Brilliant, thanks very much, appreciate the hard work you put into this
tool.
